apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-failure-predictor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-failure-predictor
  template:
    metadata:
      labels:
        app: k8s-failure-predictor
    spec:
      containers:
        - name: k8s-failure-predictor
          image: pavithracp1909/k8s-failure-predictor:v1
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-failure-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: k8s-failure-predictor

